### ISSUE TITLE
1.10.5 multipart/alternative boundaries are different in header and body

### ISSUE THREAD

**Issue by francoisstark333** [pear/Mail_Mime#19]
-No change in my example php code below
- upgrade to mail_mime 1.10.5, the boundary in the Content-Type: multipart/alternative header is different from the body
- downgrade to mail_mime 1.10.4, the boundary in the header is the same as in the body. Correct.
- as per the warning in the changelog of 1.10.5, I am not setting Content-Transfer-Encoding on multipart messages.  mail_mime defaults to multipart/alternative.

Example code:
$mime = new Mail_mime(array('eol' => PHP_EOL));
$mime->setTXTBody($text);
$mime->setHTMLBody($html);
$mime_params = array(
        'text_encoding' => '7bit',
        'text_charset'  => 'UTF-8',
        'html_charset'  => 'UTF-8',
        'head_charset'  => 'UTF-8'
      );
$body = $mime->get($mime_params);
$hdrs = array(
    'From' => $from,
    'Subject' => $subject,
    'To' => $to
        );
$hdrs = $mime->headers($hdrs);
$msg = '';
foreach ($hdrs as $key => $val){
    $msg .= $key.": ".$val.PHP_EOL;
}
$msg .= PHP_EOL."This is a multi-part message in MIME format.".PHP_EOL;
$msg .= $body;
echo $msg;
//----------------------------------------------------

//correct (expected) result: from 1.10.4
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="=_15b567cd99cd8009c9780e9d7d92e055"
From: XXX <noreply@xxx.com>
Subject: YYY
To: ZZZ

This is a multi-part message in MIME format.
--=_15b567cd99cd8009c9780e9d7d92e055
Content-Transfer-Encoding: 7bit
Content-Type: text/plain; charset=UTF-8

Please view this mail in a HTML-capable mail client
--=_15b567cd99cd8009c9780e9d7d92e055

//-----------------------------------------------------------------------------

Incorrect result (from 1.10.5)
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="=_06f4d55e551f6d0099afe89eaae519b2"
From: XXX <noreply@xxx.com>
Subject: YYY
To: ZZZ

This is a multi-part message in MIME format.
--=_2e148fc164447df3cad439932ec7c841
Content-Transfer-Encoding: 7bit
Content-Type: text/plain; charset=UTF-8

Please view this mail in a HTML-capable mail client
--=_2e148fc164447df3cad439932ec7c841

**Comment by alecpl** [comment]
That will be something to fix. I guess it will work properly if you do get() after headers().

**Comment by francoisstark333** [comment]
Yes - I just confirmed it.  if you call get() after headers(), the boundaries are correct.  
If you call headers() after get() in 1.10.4, it works too.
If you call headers() after get() in 1.10.5, it fails.  Boundaries are different.

**Comment by francoisstark333** [comment]
Would it be possible to add a comment in the changelog of 1.10.5 that explains the order of calling functions are important?

**Comment by alecpl** [comment]
Not possible, but I'll work on a fix and new release.

**Comment by alecpl** [comment]
Fixed. I'll create a release soon.
