### ISSUE TITLE
1.10.7 on https://packagist.org/

### ISSUE THREAD

**Issue by araab** [pear/Mail_Mime#21]
Can you please upload the 1.10.7 release to https://packagist.org/

**Comment by alecpl** [comment]
I forgot to push the tag. It's now pushed, packagist should update automatically.

**Comment by araab** [comment]
sorry to bother you again, but there is still no release.
On packagist is a hint that the package is not auto-updated.

**Comment by alecpl** [comment]
Yes, I noticed that, I asked for help on PEAR-DEV mailing list, as I have no idea why it stopped working and how to fix it.

**Comment by ashnazg** [comment]
I'm following up on this... sit tight.

**Comment by alecpl** [comment]
It's fixed now. Thanks @ashnazg
