### ISSUE TITLE
Backward slash is getting added in headers

### ISSUE THREAD

**Issue by johnrenosh** [pear/Mail_Mime#26]
After upgrading to 1.10.10, I am noticing a strange behaviour: backslash is getting added in the content

Eg:

From: "George B@@Z"<georgeb@cort.org.au> is getting changed to 
From: "\\"George" B@@Z"<georgeb@cort.org.au>

In the recipient list (To header), there is newline getting added with backslash

"Abel Thomas" <abel@mail.com> is getting changed to
 "Abel\ 
Thomas" <abel@mail.com>

**Comment by alecpl** [comment]
Could you provide a sample code to reproduce the issue?

**Comment by johnrenosh** [comment]
Not able to reproduce the 2nd issue. It comes randomly on production. Here is the snippet to reproduce first one:

```
require_once("mime.class.php");
$mail_mime	 = new Mail_mime("\n");

$from = '"George B@@Z"<georgeb@cort.org.au>';
$to = <<<EOT
"austin noronha" <austinn@cort.org.au>,"reno john" <renoj@cort.org.au>
EOT;
$subject = "Test mime";
$mailbody = "hello world";

$mail_mime->setTxtBody($mailbody);
$mail_mime->setHTMLBody($mailbody);
$mail_mime->setSubject($subject);
$mail_mime->setFrom($from);



$body = $mail_mime->get();

$extra_headers = array();
$extra_headers["To"] = $to;


$arr_hdrs = $mail_mime->headers($extra_headers);

$mime_message = "";
foreach($arr_hdrs as $key => $val)
{
	$mime_message .= $key.": ".$val."\n";
}

$mime_message .= "\n".$body;

echo  $mime_message;
```

**Comment by alecpl** [comment]
I confirm the issue. The problem is when the recipient name contains `@` character and there's no space between name and email. So, you can workaround that by adding the space, i.e. `"George B@@Z" <georgeb@cort.org.au>`.

**Comment by alecpl** [comment]
Fixed.
